## 1)

On importe les données avec: 
read.csv("C:/Users/Pol/Desktop/RStudio/Régression linéaire/ozone.txt", sep="")

Ensuite, on trace maxO3 en fonction de T12:

attach(ozone)
plot(T12,maxO3) 

maxO3 (y) en fonction de T12 (x)

Une régression linéaire peut se justifier.

# Estimation

## 2)

On calcule les moyennes empiriques:

yy=mean(maxO3)
xx=mean(T12)

Puis les estimateurs de bêta 1 puis 0:

beta1=0
a=0
b=0
for (i in 1:length(maxO3)){
a=a+(maxO3[i]-yy)*(T12[i]-xx)
b=b+((T12[i]-xx)^2)
beta1=a/b
}

sum((T12-xx)*(maxO3-yy))/sum((T12-xx)^2) (même calcul)
cov(T12,maxO3)/var(T12) (même calcul)

beta0=yy-beta1*xx

On ajoute la droite de régression:

abline(c(beta0,beta1))

Le c() est optionnel.

On ajoute ensuite les y estimés par notre modèle:

points(T12*beta1+beta0~T12)

## 3)

residus=T12*beta1+beta0-maxO3

mean(residus)

On trouve une moyenne inférieur à 10^-14, on peut estimer qu'ils sont centrés.

hist(residus)

## 4)

sigmacarre = sum(residus^2)/(length(maxO3)-2)

sigma=sigmacarre^0.5
sigma=sqrt(sigmacarre)

var(residus) (c'est toujours sigma chapeau)

varbeta0=(sigmacarre/(length(maxO3)-1))*(1+(((xx)^2)/((sum((T12-xx)^2))/111)))

varbeta1=(sigmacarre/(length(maxO3)-1))/(var(T12))

(La longueur -1 corrige la valeur pour se rapprocher de lm, pas présente dans le cours)

(sum((T12-xx)^2))/(length(maxO3)-1) = var(T12) (les deux sont égaux)


## 5)

SCE= sum((T12*beta1+beta0-yy)^2)
SCR= sum((maxO3-(T12*beta1+beta0))^2)
SCT= sum((maxO3-yy)^2)
SCE+SCR-SCT


Rcarre=SCE/SCT
1-(SCR/SCT)

ro=(sum((T12-xx)*(maxO3-yy)))/(((sum((T12-xx)^2))^0.5)*((sum((maxO3-yy)^2))^0.5))

## 6)

reg=lm(maxO3~T12)
summary(reg)

R2ajt= 1- (1-Rcarre)*(length(maxO3)-1)/(length(maxO3)-1-1)

L'avant dernier 1 correspond au nombre de valeurs explicatives.

# Intervalles de confiance et région de confiance

## 7)

Intervalles de confiances: 

quantile = qt(0.975, df = 110)

coef(reg)
coef(summary(reg))

resume=summary(reg)

beta0min= coef(resume)[1,1] - quantile*coef(resume)[1,2]
beta0max= coef(resume)[1,1] + quantile*coef(resume)[1,2]
beta1min= coef(resume)[2,1] - quantile*coef(resume)[2,2]
beta1max= coef(resume)[2,1] + quantile*coef(resume)[2,2]

confint(reg)
confint(reg, level=0.95) (pareil)

install.packages("ellipse")

library(ellipse)

plot(ellipse(reg,level=0.95))

points(coef(resume)[1,1],coef(resume)[2,1])

lines(c(beta0min, beta0min,beta0max,beta0max,beta0min), c(beta1min, beta1max,beta1max,beta1min,beta1min)) (représente de manière individuelle l'intervalle de confiance à 95%, là où l'ellipse le fait de manière simultanée)

quantile1 = qchisq(0.025,df=110)
quantile2 = qchisq(0.975,df=110)
sigmamin = (110)*(resume$sigma)^2 / quantile2
sigmamax = (110)*(resume$sigma)^2 / quantile1
sqrt(c(sigmamin,sigmamax))

predict(reg, new=data.frame(T12=40))
predict(reg, new=data.frame(T12=40), interval="confidence", level=0.95)

IC= predict(reg, new=data.frame(T12), interval="confidence", level=0.95)

T12= seq(min(T12), max(T12), length=112)

lines(T12, IC[,3], lty=2)

ICpred= predict(reg, new=data.frame(T12), interval="prediction", level=0.95)


lines(T12, ICpred[,3], lty=2)