```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
N=3
x=2

V <- matrix(0, nrow = 1 + (2^(N)) * x, ncol = N + 1)
maximiseur <- matrix(0, nrow = 1 + (2^(N)) * x, ncol = N)
V[, 1] <- (0:((2^(N)) * x))
for (n in 1 :N) {
  V[1, n + 1] <- 0
  for (k in 1:((2^(N - n)) * x)) {
    tmp <- NULL
    for (a in 0:k) {
      tmp[a + 1] <- (V[k - a + 1, n] + V[k + a + 1, n]) / 2
    }
    v <- max(tmp)
    f <- which.max(tmp)
    V[k + 1, n + 1] <- v
    maximiseur [k + 1, n] <- f - 1
  }
}

A <- matrix(0, nrow = 2^N+1, ncol = 2^N+1)
A[, 1] <- (0:2^N)
A[1,] <- (0:-2^N)
for (i in 1:(2^N+1)) {
  A[i,] <- A[1,] + i -1
}

prob <- matrix(0, nrow = 2^N+1, ncol = 2^N+1)
for (i in 0:(2^N)) {
  for (j in 0:(2^N)) {
    prob[i+1,j+1] <- dbinom(x = i, size = 2^N, prob = 0.45)*dbinom(x = j, size = 2^N, prob = 0.45)
  }
}

```

## Question 11

On cherche M pour réduire le nombre d'état possible.

On va donc chercher une valeur de M tel que le nombre d'individus au bout de 20 ans soit inférieur à M dans 95% des cas.

```{r message=FALSE, warning=FALSE}

# Variables de bases
nb_annees <- 20
alpha0 <- 5
proba_d <- 0.45
proba_b <- 0.45
nb_boucles <- 1000000
p <- matrix(nrow = 2, ncol = nb_boucles)

# On crée une matrice à 2 lignes et autant de colonnes que nécessaire,
# la première pour le coût, la seconde pour le nombre d'oiseaux au bout de 20 ans.

for (ii in 1:nb_boucles) {

  nb_oiseaux <- 2
  c <- 0

  # Ces variables ont besoin d'être remises à 0 à chaque nouvelle boucle et on retire les historiques.

  for (i in 2:(nb_annees + 1)) {
    if (nb_oiseaux != 0) {
      for (x in 1:nb_oiseaux) {
        d <- runif(1, min = 0, max = 1)
        b <- runif(1, min = 0, max = 1)
        if (d < proba_d) {
          nb_oiseaux <- nb_oiseaux - 1
        }
        if (b < proba_b) {
         nb_oiseaux <- nb_oiseaux + 1
        }
      }
    }
  }

  # On ajoute la récompense finale
  if (nb_oiseaux == 0) {
    c <- c - alpha0
  } else {
    c <- c + nb_oiseaux
  }

  p[1, ii] <- c
  p[2, ii] <- nb_oiseaux

  # On rajoute le ii-ème gain final et nombre d'oiseaux à la ii-ème place de la matrice.

}
```

```{r message=FALSE, warning=FALSE}
print("Estimation du gain:")
rowMeans(p)
max(p[1,])
```

```{r message=FALSE, warning=FALSE}
a <- 0
#r <- c()
for (i in 1:nb_boucles) {
  if (p[2, i] > 0) {
    a <- a + 1
    #r <- c(r, p[2, i])
  }
}
a / nb_boucles*100
#mean(r)

b=0

for (i in 1:a) {
  if (r[i] > 39) {
    b <- b + 1
  }
}

b/a*100

# 27 pour 98.93504% des cas survivants.
# 20 pour 98.9659% de tous les cas.
# 39 pour 99.89713 des cas survivants.
# 32 pour 99.8887 de tous les cas.

```


```{r message=FALSE, warning=FALSE}

M = 39

p_birth=c(0.45, 0.5,  0.45)

p_death=c(0.45, 0.45, 0.35)

population = 2

transition_density = function(population, action) {
      # distribution of birth
      birth_density = dbinom(0:population, population, p_birth[action])

      # distribution of death
      death_density = dbinom(0:population, population, p_death[action])

      result = rep(0, M+1)

      # distribution of population + birth - death
      sum_density = convolve(birth_density, death_density, type="open")
      result = sum_density

      # make sum_density have the right dimensions
      result = result[0:M+1]
      # remove NA
      result[is.na(result)] = 0

      result[M+1] = sum(tail(sum_density, -M))

      result
}

N <- 20

# Matrices de transition
Q <- array(0, dim <- c(4, 4, 3))

# Ne rien faire : action 0
Q[, , 1] <- matrix(c(0, 0.8, 0,   0.2,
                    0, 0,   0.8, 0.2,
                    0, 0,   0.5, 0.5,
                    0, 0,   0,   0), nrow = 4, byrow = TRUE)

# Entretien : action 1
Q[, , 2] <- matrix(c(0.75, 0.25, 0,    0,
                    0,     0.6,  0.3,  0.1,
                    0,     0,    0.75, 0.25,
                    0,     0,    0,    0), nrow = 4, byrow = TRUE)

# Rénovation : action 2
Q[, , 3] <- matrix(c(0, 0, 0, 0,
                     1, 0, 0, 0,
                     1, 0, 0, 0,
                     1, 0, 0, 0), nrow = 4, byrow = TRUE)

#Chacune des lignes de 0 rajoutées aurait pu être n'importe quel nombre,
#cela n'a pas d'importance (pas besoin de respecter les propriétés
#de matrice de transition pour ces lignes)

# Récompense instantanée
rec <- matrix(c(0, -0.1, -0.2), nrow = 3)

# Récompense finale
gain <- c(-5,x)

for (n in 1:N) {
  for (x in 1:4) {
    tmp <- rec[x, ] + V[, n] %*% Q[x, , ]
    pi[x, n] <- which.max(tmp)
    V[x, n + 1] <- max(tmp)
  }
}

N=20
M=39

V <- matrix(0, nrow = M+1, ncol = N + 1)
C <- matrix(0, nrow = M+1, ncol = N + 1)
maximiseur <- matrix(0, nrow = M+1, ncol = N)
V[, 1] <- (0:M)
C[, 1] <- (0:M)
C[1, 1] <- -5
for (n in 1:N) {
  V[1, n + 1] <- 0
  for (k in 1:M) {
    tmp <- NULL
    for (a in 1:3) {
      tmp[a] <- rec[a, ] + V[, n] %*% transition_density(floor(max(V[, n])),a)
    }
    f <- which.max(tmp)
    v <- max(tmp)
    V[k + 1, n + 1] <- V[, n] %*% transition_density(floor(max(V[, n])),f)
    C[k + 1, n + 1] <- C[k + 1, n] + rec[f]
    maximiseur [k + 1, n] <- f - 1
  }
}
```
